spring:
  application:
    name: crm-loyalty-core
  profiles:
    default: local
    active: ${spring.profiles.default}
  config:
    import:
      - crm-database.yml
      - crm-jpa.yml
      - crm-tenant.yml



logging:
  level:
    org:
      springframework:
        transaction:
          interceptor: trace